<?php
/**
 * Constants
 *
 * @author Virgil-Adrian Teaca - virgil@giulianaeassociati.com
 * @version 3.0
 */

/**
 * Setup the Config API Mode.
 * For using the 'database' mode, you need to have a database, with a table generated by 'scripts/nova_options'
 */
define('CONFIG_STORE', 'files'); // Supported: "files", "database"

/**
 * define the database config
 */

define('DB_TYPE', 'mysql');
define('DB_HOST', 'localhost');
define('DB_NAME', 'momentum_ventures');
define('DB_USER', 'momVentures');
define('DB_PASS', '9QgBucL[oiX#');

define('PREFIX', 'momentum_');

define('SESSION_PREFIX', 'momentum_');
